version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "."
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      git:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    groups:
      gha:
        patterns:
          - "*"
